version: "3.8"
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - coursier-cache:/root/.cache/coursier
      - ivy-cache:/root/.ivy2/cache
      - sbt-cache:/root/.sbt
    command: bin/run

volumes:
  coursier-cache:
  ivy-cache:
  sbt-cache:
